project_name: cuemod
dist: ./bin
before:
  hooks:
    - go mod download -x
changelog:
  filters:
    exclude:
      - '^docs'
      - '^chore'
builds:
  - id: cuem
    dir: ./cmd/cuem
    binary: cuem

    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/octohelm/cuemod/internal/version.Version={{ .Version }}+sha.{{ .FullCommit }}
    mod_timestamp: '{{ .CommitTimestamp }}'

dockers:
  - use: buildx
    image_templates:
      - "docker.io/octohelm/cuem:latest"
      - "docker.io/octohelm/cuem:{{ .Tag }}"
    dockerfile: ./cmd/cuem/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64,linux/amd64"
