// Code generated by go generate. DO NOT EDIT.

//go:generate rm pkg.go
//go:generate go run ../../gen/gen.go

package os

import (
	"github.com/octohelm/cuemod/pkg/cue/internal/cuelang.org/go/internals/core/adt"
	internal "github.com/octohelm/cuemod/pkg/cue/internal/cuelang.org/go/pkg/internals"
)

func init() {
	internal.Register("tool/os", pkg)
}

var _ = adt.TopKind // in case the adt package isn't used

var pkg = &internal.Package{
	Native: []*internal.Builtin{},
	CUE: `{
	Value: bool | number | *string | null
	Name:  !="" & !~"^[$]"
	Setenv: {
		{
			[Name]: Value
		}
		$id: "tool/os.Setenv"
	}
	Getenv: {
		{
			[Name]: Value
		}
		$id: "tool/os.Getenv"
	}
	Environ: {
		{
			[Name]: Value
		}
		$id: "tool/os.Environ"
	}
	Clearenv: {
		$id: "tool/os.Clearenv"
	}
}`,
}
