name: goreleaser

on:
  push:
    branches:
      - "*"
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login to docker.io
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}

      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          install-only: true

      - name: Build images
        env:
          NAMESPACES: ${{ github.event_name != 'pull_request' && 'docker.io/octohelm ghcr.io/octohelm' || 'localhost:5000' }}
        run: |-
          export COMMIT_SHA=${{ github.sha }}
          export TAG=main
          export PUSH=true
          if [[ ${{ github.ref }} == "refs/tags/v"* ]]; then
            export TAG=$(echo ${{ github.ref }} | sed -e "s/refs\/tags\/v//")
          fi
          make dockerx

      - uses: goreleaser/goreleaser-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}